## Упражнения по библиотеке Numpy

In [44]:
import numpy as np

**1.** Дан случайный массив, поменять знак у элементов, значения которых между 3 и 8

In [45]:
array1 = np.random.randint(1, 10, 10)
print(array1)
array1[(array1 > 3) & (array1 < 8)] *= -1
print(array1)

[5 3 5 3 4 9 4 9 6 4]
[-5  3 -5  3 -4  9 -4  9 -6 -4]


**2.** Заменить максимальный элемент случайного массива на 0

In [47]:
array2 = np.random.randint(1, 10, 10)
print(array2)
array2[array2.argmax()]=0
print(array2)

[5 1 7 2 8 2 2 1 6 3]
[5 1 7 2 0 2 2 1 6 3]


**3.** Построить прямое произведение массивов (все комбинации с каждым элементом). На вход подается двумерный массив

In [48]:
array3a = np.random.randint(10, size=(3, 5))
print(array3a)
array3b = np.random.randint(10, size=(3, 5))
print('\n', array3b)
total = np.multiply(array3a, array3b)
print('\n', total)

[[1 8 7 1 4]
 [9 8 2 9 8]
 [9 9 4 3 2]]

 [[2 6 9 9 8]
 [0 2 3 6 5]
 [4 3 7 1 8]]

 [[ 2 48 63  9 32]
 [ 0 16  6 54 40]
 [36 27 28  3 16]]


**4.** Даны 2 массива A (8x3) и B (2x2). Найти строки в A, которые содержат элементы из каждой строки в B, независимо от порядка элементов в B

In [49]:
#a = np.random.randint(0, 10, (8, 3))
#b = np.random.randint(0, 10, (2, 2))
#print(a)
#print('\n', b)

**5.** Дана 10x3 матрица, найти строки из неравных значений (например строка [2,2,3] остается, строка [3,3,3] удаляется)

In [50]:
array5 = np.random.randint(4, size=(10, 3))
print(array5, '\n')
new = []
for i in array5:
    new.append(not np.all(i == i[0]))
total = array5[new]
print(total)

[[3 1 3]
 [3 0 2]
 [3 2 0]
 [0 2 0]
 [0 3 2]
 [2 2 2]
 [2 3 3]
 [3 3 3]
 [0 0 2]
 [2 1 1]] 

[[3 1 3]
 [3 0 2]
 [3 2 0]
 [0 2 0]
 [0 3 2]
 [2 3 3]
 [0 0 2]
 [2 1 1]]


**6.** Дан двумерный массив. Удалить те строки, которые повторяются

In [32]:
array6 = np.random.randint(2, size=(10, 2))
print(array6, '\n')
array6 = np.unique(array6, axis=0)
print(array6)

[[1 0]
 [1 0]
 [1 0]
 [0 1]
 [1 0]
 [0 0]
 [0 0]
 [0 1]
 [0 1]
 [1 0]] 

[[0 0]
 [0 1]
 [1 0]]


______
______

Для каждой из следующих задач (1-5) нужно привести 2 реализации – одна без использования numpy (cчитайте, что там, где на входе или выходе должны быть numpy array, будут просто списки), а вторая полностью векторизованная с использованием numpy (без использования питоновских циклов/map/list comprehension).


__Замечание 1.__ Можно считать, что все указанные объекты непустые (к примеру, в __задаче 1__ на диагонали матрицы есть ненулевые элементы).

__Замечание 2.__ Для большинства задач решение занимает не больше 1-2 строк.

___

* __Задача 1__: Подсчитать произведение ненулевых элементов на диагонали прямоугольной матрицы.  
 Например, для X = np.array([[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]]) ответ 3.

In [51]:
X = np.array([[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]])
print(np.prod(np.diag(X), where = np.diag(X) !=0))

3


In [52]:
X = [[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]]
product = 1
for i in range(len(X)):
    for j in range(len(X[i])):
        if i==j and (X[i][j]) != 0:
            product *= (X[i][j])
print(product)

3


* __Задача 2__: Даны два вектора x и y. Проверить, задают ли они одно и то же мультимножество.  
  Например, для x = np.array([1, 2, 2, 4]), y = np.array([4, 2, 1, 2]) ответ True.

In [53]:
x = np.array([1, 2, 2, 4])
y = np.array([4, 2, 1, 2])
x.sort() == y.sort()

True

In [54]:
x = [1, 2, 2, 4]
y = [4, 2, 1, 2]
x.sort() == y.sort()

True

* __Задача 3__: Найти максимальный элемент в векторе x среди элементов, перед которыми стоит ноль. 
 Например, для x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0]) ответ 5.

In [55]:
x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0])
np.max((x[1:][(x==0)[:-1]]))

5

In [56]:
x = [6, 2, 0, 3, 0, 0, 5, 7, 0]
biggest = 0
for i in range(1, len(x)):
    if x[i-1] == 0 and x[i]>biggest:
        biggest = x[i]
print(biggest)

5


* __Задача 4__: Реализовать кодирование длин серий (Run-length encoding). Для некоторого вектора x необходимо вернуть кортеж из двух векторов одинаковой длины. Первый содержит числа, а второй - сколько раз их нужно повторить.  
 Например, для x = np.array([2, 2, 2, 3, 3, 3, 5]) ответ (np.array([2, 3, 5]), np.array([3, 3, 1])).

In [57]:
x = np.array([2, 2, 2, 3, 3, 3, 5])
np.unique(x, return_counts=False)
np.unique(x, return_counts=True)

(array([2, 3, 5]), array([3, 3, 1], dtype=int64))

In [58]:
x = np.array([1, 1, 7, 7, 9, 9, 9])
np.unique(x, return_counts=False)
np.unique(x, return_counts=True)

(array([1, 7, 9]), array([2, 2, 3], dtype=int64))

In [59]:
x = [1, 1, 7, 7, 9, 9, 9]
array1 = []
array2 = []
for i in x:
    if i not in array1:
        array1.append(i)
print(array1)
y=0
for i in array1:
    if i not in array2:
        array2.append(x.count(array1[y]))
        y+=1
print(array2)

[1, 7, 9]
[2, 2, 3]


* __Задача 5__: Даны две выборки объектов - X и Y. Вычислить матрицу евклидовых расстояний между объектами. Сравните с функцией scipy.spatial.distance.cdist по скорости работы.

In [60]:
# your code

_______
________

* #### __Задача 6__: CrunchieMunchies __*__

Вы работаете в отделе маркетинга пищевой компании MyCrunch, которая разрабатывает новый вид вкусных, полезных злаков под названием **CrunchieMunchies**.

Вы хотите продемонстрировать потребителям, насколько полезны ваши хлопья по сравнению с другими ведущими брендами, поэтому вы собрали данные о питании нескольких разных конкурентов.

Ваша задача - использовать вычисления Numpy для анализа этих данных и доказать, что ваши **СrunchieMunchies** - самый здоровый выбор для потребителей.


In [61]:
import numpy as np

1. Просмотрите файл cereal.csv. Этот файл содержит количества калорий для различных марок хлопьев. Загрузите данные из файла и сохраните их как calorie_stats.

In [62]:
calorie_stats = np.loadtxt("./data/cereal.csv", delimiter=",")
calorie_stats

array([ 70., 120.,  70.,  50., 110., 110., 110., 130.,  90.,  90., 120.,
       110., 120., 110., 110., 110., 100., 110., 110., 110., 100., 110.,
       100., 100., 110., 110., 100., 120., 120., 110., 100., 110., 100.,
       110., 120., 120., 110., 110., 110., 140., 110., 100., 110., 100.,
       150., 150., 160., 100., 120., 140.,  90., 130., 120., 100.,  50.,
        50., 100., 100., 120., 100.,  90., 110., 110.,  80.,  90.,  90.,
       110., 110.,  90., 110., 140., 100., 110., 110., 100., 100., 110.])

2. В одной порции CrunchieMunchies содержится 60 калорий. Насколько выше среднее количество калорий у ваших конкурентов?

Сохраните ответ в переменной average_calories и распечатайте переменную в терминале

In [63]:
average_calories = np.average(calorie_stats)
average_calories

106.88311688311688

3. Корректно ли среднее количество калорий отражает распределение набора данных? Давайте отсортируем данные и посмотрим.

Отсортируйте данные и сохраните результат в переменной calorie_stats_sorted. Распечатайте отсортированную информацию

In [64]:
calorie_stats_sorted = np.sort(calorie_stats)
calorie_stats_sorted

array([ 50.,  50.,  50.,  70.,  70.,  80.,  90.,  90.,  90.,  90.,  90.,
        90.,  90., 100., 100., 100., 100., 100., 100., 100., 100., 100.,
       100., 100., 100., 100., 100., 100., 100., 100., 110., 110., 110.,
       110., 110., 110., 110., 110., 110., 110., 110., 110., 110., 110.,
       110., 110., 110., 110., 110., 110., 110., 110., 110., 110., 110.,
       110., 110., 110., 110., 120., 120., 120., 120., 120., 120., 120.,
       120., 120., 120., 130., 130., 140., 140., 140., 150., 150., 160.])

4. Похоже, что большинство значений выше среднего. Давайте посмотрим, является ли медиана наиболее корректным показателем набора данных.

Вычислите медиану набора данных и сохраните свой ответ в median_calories. Выведите медиану, чтобы вы могли видеть, как она сравнивается со средним значением.

In [65]:
median_calories = np.median(calorie_stats_sorted)
median_calories

110.0

5. В то время как медиана показывает, что по крайней мере половина наших значений составляет более 100 калорий, было бы более впечатляюще показать, что значительная часть конкурентов имеет более высокое количество калорий, чем CrunchieMunchies.

Рассчитайте различные процентили и распечатайте их, пока не найдете наименьший процентиль, превышающий 60 калорий. Сохраните это значение в переменной nth_percentile.

In [66]:
print(np.percentile(calorie_stats_sorted, 1))
print(np.percentile(calorie_stats_sorted, 2))
print(np.percentile(calorie_stats_sorted, 3))
print(np.percentile(calorie_stats_sorted, 4))
print(np.percentile(calorie_stats_sorted, 3.5))
print(np.percentile(calorie_stats_sorted, 3.4))
print(np.percentile(calorie_stats_sorted, 3.3))
print(np.percentile(calorie_stats_sorted, 3.2))
print(np.percentile(calorie_stats_sorted, 3.25))
print(np.percentile(calorie_stats_sorted, 3.28))
print(np.percentile(calorie_stats_sorted, 3.29))
nth_percentile = 3.29
nth_percentile

50.0
50.0
55.599999999999994
70.0
63.2
61.68
60.16
58.64
59.400000000000006
59.855999999999995
60.007999999999996


3.29

6. Хотя процентиль показывает нам, что у большинства конкурентов количество калорий намного выше, это неудобная концепция для использования в маркетинговых материалах.

Вместо этого давайте подсчитаем процент хлопьев, в которых содержится более 60 калорий на порцию. Сохраните свой ответ в переменной more_calories и распечатайте его

In [67]:
more_calories = np.count_nonzero(calorie_stats_sorted > 60) / len(calorie_stats_sorted) * 100
more_calories

96.1038961038961

7. Это действительно высокий процент. Это будет очень полезно, когда мы будем продвигать CrunchieMunchies. Но один вопрос заключается в том, насколько велики различия в наборе данных? Можем ли мы сделать обобщение, что в большинстве злаков содержится около 100 калорий или разброс еще больше?

Рассчитайте величину отклонения, найдя стандартное отклонение, Сохраните свой ответ в calorie_std и распечатайте на терминале. Как мы можем включить эту ценность в наш анализ?

In [68]:
calorie_std = np.std(calorie_stats_sorted)
calorie_std

19.35718533390827

8. Напишите короткий абзац, в котором кратко изложите свои выводы и то, как, по вашему мнению, эти данные могут быть использованы в интересах Mycrunch при маркетинге CrunchieMunchies.

<b>Если человек следит за калориями, он может самостоятельно регулировать их количество -- уменьшая либо увеличивая количество хлопьев в своей тарелке. Калорийность CrunchieMunchies существенно ниже, чем калорийность большинства хлопьев. Та часть потребителей, которая подсчитывает калории, скорее ограничивает их количество, чем ищет лёгкий способ углеводных загрузок перед соревнованиями. Поэтому реклама должна быть направлена на тех, кто следит за весом и фигурой. Важный момент -- доступность информации о составе и калорийности, хорошим решением будет разместить на упаковке не только стандартную информацию о пищевой ценности в одной порции, но и в ста граммах -- для удобства подсчётов. Также важен состав. Поскольку CrunchieMunchies содержат существенно меньше калорий при равном весе продукции, можно предположить, что это происходит за счёт высокого содержания клетчатки -- и если это деёствительно так, об этом следует упомянуть при продвижении.</b>